services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-xyzdb}
    ports:
      - "5454:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-8081}:${SERVER_PORT:-8081}"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      DB_NAME: ${DB_NAME:-xyzdb}
      SERVER_PORT: ${SERVER_PORT:-8081}
      SWAGGER_USER: ${SWAGGER_USER}
      SWAGGER_PASS: ${SWAGGER_PASS}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy