package main

import (
	"log"
	"net/http"
	"os"
	"pt-xyz-multifinance/config"
	"pt-xyz-multifinance/internal/handler"
	customMiddleware "pt-xyz-multifinance/internal/middleware" // Alias untuk middleware internal
	"pt-xyz-multifinance/internal/repository"
	"pt-xyz-multifinance/internal/usecase"
	"pt-xyz-multifinance/pkg"

	_ "pt-xyz-multifinance/docs" // generated by swag init

	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title           PT-XYZ Multifinance API
// @version         1.0
// @description     API untuk PT-XYZ Multifinance
// @host            localhost:8080
// @BasePath        /
// @securityDefinitions.apikey BearerAuth
// @type            http
// @scheme          bearer
// @bearerFormat    JWT
// @name            Authorization
// @in              header
func main() {
	// Load .env file (kalau ada)
	_ = godotenv.Load()

	cfg := config.New()
	db := pkg.NewDatabase(cfg)
	defer db.Close()

	// Inisialisasi Customer
	customerRepo := repository.NewCustomerRepository(db)
	customerUC := usecase.NewCustomerUsecase(customerRepo)
	customerHandler := handler.NewCustomerHandler(customerUC)

	// Inisialisasi User
	userRepo := repository.NewUserRepository(db)
	userUC := usecase.NewUserUsecase(userRepo)
	userHandler := handler.NewUserHandler(userUC)

	e := echo.New()

	// Ambil username dan password Swagger dari .env/env
	swaggerUser := os.Getenv("SWAGGER_USER")
	swaggerPass := os.Getenv("SWAGGER_PASS")

	// Gunakan middleware.BasicAuth dari echo/v4
	swaggerBasicAuth := middleware.BasicAuth(func(username, password string, c echo.Context) (bool, error) {
		if username == swaggerUser && password == swaggerPass {
			return true, nil
		}
		return false, nil
	})

	// Swagger endpoint
	e.GET("/swagger/*", echoSwagger.WrapHandler, swaggerBasicAuth)

	// Health check endpoint
	e.GET("/health", HealthCheck)

	// API routes
	api := e.Group("/api/v1")

	// Customer routes (dengan JWT middleware dari internal/middleware)
	api.POST("/customers", customerHandler.Create, customMiddleware.JWTMiddleware)
	api.GET("/customers/:id", customerHandler.GetByID, customMiddleware.JWTMiddleware)

	// User routes (tanpa middleware, untuk register & login)
	api.POST("/register", userHandler.Register)
	api.POST("/login", userHandler.Login)

	// Start server
	e.Logger.Fatal(e.Start(":" + cfg.ServerPort))
}

// HealthCheck godoc
// @Summary      Health Check
// @Description  Cek status service
// @Tags         Utility
// @Success      200  {object}  map[string]interface{}
// @Router       /health [get]
func HealthCheck(c echo.Context) error {
	log.Println("Health check endpoint hit")
	return c.JSON(http.StatusOK, map[string]interface{}{
		"status":  "ok",
		"message": "Service is healthy",
	})
}
