package main

import (
	"log"
	"net/http"
	"os"
	"pt-xyz-multifinance/config"
	"pt-xyz-multifinance/internal/handler"
	"pt-xyz-multifinance/internal/repository"
	"pt-xyz-multifinance/internal/usecase"
	"pt-xyz-multifinance/pkg"

	_ "pt-xyz-multifinance/docs" // generated by swag init

	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title           PT-XYZ Multifinance API
// @version         1.0
// @description     API untuk PT-XYZ Multifinance
// @host            localhost:8080
// @BasePath        /
func main() {
	// Load .env file (kalau ada)
	_ = godotenv.Load()

	cfg := config.New()
	db := pkg.NewDatabase(cfg)
	defer db.Close()

	customerRepo := repository.NewCustomerRepository(db)
	customerUC := usecase.NewCustomerUsecase(customerRepo)
	customerHandler := handler.NewCustomerHandler(customerUC)

	e := echo.New()

	// Ambil username dan password Swagger dari .env/env
	swaggerUser := os.Getenv("SWAGGER_USER")
	swaggerPass := os.Getenv("SWAGGER_PASS")

	swaggerBasicAuth := middleware.BasicAuth(func(username, password string, c echo.Context) (bool, error) {
		if username == swaggerUser && password == swaggerPass {
			return true, nil
		}
		return false, nil
	})

	e.GET("/swagger/*", echoSwagger.WrapHandler, swaggerBasicAuth)

	e.GET("/health", HealthCheck)

	// routes
	api := e.Group("/api/v1")
	api.POST("/customers", customerHandler.Create)
	api.GET("/customers/:id", customerHandler.GetByID)

	e.Logger.Fatal(e.Start(":" + cfg.ServerPort))
}

// HealthCheck godoc
// @Summary      Health Check
// @Description  Cek status service
// @Tags         Utility
// @Success      200  {object}  map[string]interface{}
// @Router       /health [get]
func HealthCheck(c echo.Context) error {
	log.Println("Health check endpoint hit")
	return c.JSON(http.StatusOK, map[string]interface{}{
		"status":  "ok",
		"message": "Service is healthy",
	})
}
