basePath: /
definitions:
  dto.CreateCustomerRequest:
    properties:
      birth_date:
        description: '"YYYY-MM-DD"'
        type: string
      birth_place:
        type: string
      full_name:
        type: string
      ktp_photo_url:
        type: string
      legal_name:
        type: string
      nik:
        type: string
      salary:
        type: number
      selfie_photo_url:
        type: string
    required:
    - full_name
    - legal_name
    - nik
    type: object
  dto.CustomerResponse:
    properties:
      birth_date:
        type: string
      birth_place:
        type: string
      created_at:
        type: string
      full_name:
        type: string
      id:
        type: string
      ktp_photo_url:
        type: string
      legal_name:
        type: string
      nik:
        type: string
      salary:
        type: number
      selfie_photo_url:
        type: string
      updated_at:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  dto.RegisterResponse:
    properties:
      email:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API untuk PT-XYZ Multifinance
  title: PT-XYZ Multifinance API
  version: "1.0"
paths:
  /api/v1/customers:
    post:
      consumes:
      - application/json
      description: Create/register a new customer
      parameters:
      - description: Customer Data
        in: body
        name: customer
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCustomerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CustomerResponse'
        "400":
          description: invalid request or validation error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Register new customer
      tags:
      - customer
  /api/v1/customers/{id}:
    get:
      description: Get detail of customer by ID
      parameters:
      - description: Customer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CustomerResponse'
        "404":
          description: customer not found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get customer by ID
      tags:
      - customer
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and generate a token
      parameters:
      - description: Login Credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: invalid request or validation error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - user
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Create/register a new user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
        "400":
          description: invalid request or validation error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register new user
      tags:
      - user
  /health:
    get:
      description: Cek status service
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health Check
      tags:
      - Utility
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
